### ISSUE TITLE
How to run on Chromebook/ChromeOS?

### ISSUE THREAD

**Issue by redditcrazy** [9-FS/nhentai_archivist#14]
Basically the title. I've got a Samsung Chromebook Pro including a Linux installation and I cant seem to figure out what terminal commands I would need to run in order to install and utilize this project-and I would very much love to.

**Comment by 9-FS** [comment]
Have you read the readme?

**Comment by sam-k0** [comment]
Download the linux release from release tab
1.  Add the `x` flag if necessary. `sudo chmod +x <executable>`
2.  Execute the program once to create a default ./config/.env.
3.  Execute the program again and enter the nHentai ID you want to download separated by spaces.
