### ISSUE TITLE
Feature Request: Add flag for .webp conversion and optional compression level.

### ISSUE THREAD

**Issue by Su13n** [9-FS/nhentai_archivist#23]
Converting the images to .webp before packing them as .cbz could save hundreds of GB without loss of quality. Even with some compression applied, degradation wouldn't necessarily be noticeable while file size gets reduced significantly.

**Comment by 9-FS** [comment]
This is a very interesting feature request and I'm inclined to accept it. Are you aware of a good Rust library that faciliates conversion to webp?

**Comment by Su13n** [comment]
> This is a very interesting feature request and I'm inclined to accept it. Are you aware of a good Rust library that faciliates conversion to webp?

The [webp](https://crates.io/crates/webp/0.3.0/dependencies) crate was specifically designed for .webp conversion and lossless/lossy compression. Afaik it can also be used without the Image crate.

**Comment by 9-FS** [comment]
Wow, that's great! Thanks!

Unfortunately, university just kicked in again and earliest I can seriously evaluate this will be in 2 weeks. I will take a look if I can bring down the performance penality to an acceptable level with multi threading. Thinking about a similar implementation as I did with the image download. Feel free to open a pull request if you want to be listed as a contributor and we'll work it out together.

And by the way, this is my first non-trivial Rust project so I'm a beginner too. ;) But the best way to learn is to just do stuff, so I'm happy you came forward with your proposition.

**Comment by 9-FS** [comment]
I have decided that conversion would add too much complexity and is therefore out of scope for this project. Seems like it would be outdated anyways now that nhentai.net has switched their new media backend to webp. Conversion of older media can be done manually with `CLEANUP_TEMPORARY_FILES = false`, if desired.
