### ISSUE TITLE
Feature - Export ComincInfo.xml from DB

### ISSUE THREAD

**Issue by B4rbat0s** [9-FS/nhentai_archivist#27]
Add an option to export/create just ComincInfo.xml files from data in the DB.
Use case would be to keep the same tag format and content for already removed galleries which were then sourced from different websites.

Alternatively add a config option to create correctly named empty folders with the ComicInfo.xml and save them in a FAILED/MISSING root folder in the library when 404 errors/failed downloads occur.

**Comment by 9-FS** [comment]
I currently have no plans to add a pure metadata export feature, sorry.

At the moment, setting `CLEANUP_TEMPORARY_FILES = false` will result in:

1. download all images, cancel if unsuccessful
1. create CBZ
1. add an extra ComicInfo.xml to the temporary files directory

I can offer you to change this order, so in case of a failed image download the ComicInfo.xml would still be created. Would this satisfy your requirements?
