### ISSUE TITLE
Return of the "error returned from database" message

### ISSUE THREAD

**Issue by shinji257** [9-FS/nhentai_archivist#34]
This is the same as before and I think the fail point is the same as before as well.  After a while it seems to fail to update the database for unknown reasons.  It suddenly says the table Hentai doesn't exist then follows with saying the table Tag doesn't exist.  If I download the affected item manually with just the one (let's say 60150) then it does so without issue.

Log: https://gist.github.com/shinji257/e595c696e0f159f591d93a0b7dcbdb55

I have a bunch more from that session because I left the house and came back to it.  There are also 429s in there but it seems that came later as the program was spamming the API with requests as a result of it failing to interact with the database.

**Comment by 9-FS** [comment]
Yeah this error is likely a result of your previous ticket.
