### ISSUE TITLE
Skip downloaded id without it being in the hentai directory

### ISSUE THREAD

**Issue by Unknown7001** [9-FS/nhentai_archivist#41]
After archiving about 300k books, my hard drive (1st) is reaching its limited capacity. I would like to move the downloaded books to another hard disk (2nd hard disk), while still being able to update the archive on the existing hard disk (1st hard disk). I believe the db.sqlite recorded all of my previously downloaded books so there is no need for the physical books to be in the hentai folder. Am I right?

**Comment by 9-FS** [comment]
If you tell nHentai Archivist to download something, it will do so and only skip if the file already exists in `LIBRARY_PATH`. Managing libraries in multiple locations is beyond the scope of this tool.

I recommend solving this problem properly on the file system level, for example by implementing a RAID5 array or an Unraid array.
