### ISSUE TITLE
Database Error: Code 1

### ISSUE THREAD

**Issue by YaBoyHankHill** [9-FS/nhentai_archivist#42]
While trying to run the program recently, I have only gotten the following error while trying to launch in server mode. I have tried recreating the .env file and removing the database files to allow them to be replaced by fresh versions, but the error still occurs

![Error Code Example](https://github.com/user-attachments/assets/ef943d4d-3cba-44d9-902d-01a5209b3059)

**Comment by 9-FS** [comment]
Please paste your configuration and rerun with `DEBUG = true`.

**Comment by YaBoyHankHill** [comment]
[nhentai_archivist] DEBUG Loaded Config { CF_CLEARANCE: Some(""), CLEANUP_TEMPORARY_FILES: Some(true), CSRFTOKEN: Some("TOKEN VALUE"), DATABASE_URL: "./db/db.sqlite", DEBUG: Some(true), DONTDOWNLOADME_FILEPATH: None, DOWNLOADME_FILEPATH: Some("./config/downloadme.txt"), LIBRARY_PATH: "./hentai/", LIBRARY_SPLIT: Some(10000), NHENTAI_TAGS: Some(["language:\"english\", -tag:\"futanari\", -tag:\"scat\", -tag:\"urination\", -tag:\"bestiality\", -tag:\"shemale\", -tag:\"yaoi\""]), SLEEP_INTERVAL: Some(50000), USER_AGENT: Some("Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:132.0) Gecko/20100101 Firefox/132.0") }.
                      [reqwest::connect] DEBUG starting new connection: https://nhentai.net/
                      [hyper_util::client::legacy::connect::dns] DEBUG resolve; host=nhentai.net
                      [hyper_util::client::legacy::connect::dns] DEBUG resolving host="nhentai.net"
                      [hyper_util::client::legacy::connect::http] DEBUG connecting to 104.27.206.92:443
                      [hyper_util::client::legacy::connect::http] DEBUG connected to 104.27.206.92:443
                      [hyper_util::client::legacy::pool] DEBUG pooling idle connection for ("https", nhentai.net)
                      [nhentai_archivist::main_inner] ERROR Test connecting to "https://nhentai.net/api/galleries/search?query=language%3Aenglish&page=1" failed with status code 503 Service Unavailable.
                      [nhentai_archivist::main_inner] INFO  Sleeping for 50,00 ks...

**Comment by 9-FS** [comment]
Please paste your configuration.

**Comment by YaBoyHankHill** [comment]
CF_CLEARANCE = ""
CLEANUP_TEMPORARY_FILES = true
CSRFTOKEN = "Token Value"
DATABASE_URL = "./db/db.sqlite"
DOWNLOADME_FILEPATH = "./config/downloadme.txt"
LIBRARY_PATH = "./hentai/"
LIBRARY_SPLIT = 10000
NHENTAI_TAGS = ['language:"english", -tag:"futanari", -tag:"scat", -tag:"urination", -tag:"bestiality", -tag:"shemale", -tag:"yaoi"']
SLEEP_INTERVAL = 50000
USER_AGENT = "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:132.0) Gecko/20100101 Firefox/132.0"
DEBUG = true

**Comment by YaBoyHankHill** [comment]
[reqwest::connect] DEBUG starting new connection: https://nhentai.net/
                      [hyper_util::client::legacy::connect::dns] DEBUG resolve; host=nhentai.net
                      [hyper_util::client::legacy::connect::dns] DEBUG resolving host="nhentai.net"
                      [hyper_util::client::legacy::connect::http] DEBUG connecting to 104.27.206.92:443
                      [hyper_util::client::legacy::connect::http] DEBUG connected to 104.27.206.92:443
[2024-11-04T00:41:05] [cookie_store::cookie_store] DEBUG inserting secure cookie 'session-affinity'
                      [sqlx::query] DEBUG summary="PRAGMA foreign_keys = ON; …" db.statement="\n\nPRAGMA foreign_keys = ON;\n" rows_affected=0 rows_returned=0 elapsed=157.9µs elapsed_secs=0.0001579
                      [nhentai_archivist::connect_to_db] INFO  Connected to database at "./db/db.sqlite".
                      [nhentai_archivist::get_hentai_id_list] INFO  No hentai ID list found at "./config/downloadme.txt".
                      [nhentai_archivist::get_hentai_id_list] INFO  "NHENTAI_TAGS" are set.
                      [reqwest::connect] DEBUG starting new connection: https://nhentai.net/
                      [hyper_util::client::legacy::connect::dns] DEBUG resolve; host=nhentai.net
                      [hyper_util::client::legacy::connect::dns] DEBUG resolving host="nhentai.net"
                      [hyper_util::client::legacy::connect::http] DEBUG connecting to 104.27.207.92:443
                      [hyper_util::client::legacy::connect::http] DEBUG connected to 104.27.207.92:443
                      [cookie_store::cookie_store] DEBUG inserting secure cookie 'session-affinity'
                      [hyper_util::client::legacy::pool] DEBUG pooling idle connection for ("https", nhentai.net)
                      [nhentai_archivist::search_api] WARN  Saving hentai metadata page 1 / <unknown> in database failed with: error returned from database: (code: 1) near ";": syntax error
                      [sqlx::query] DEBUG summary="PRAGMA foreign_keys = OFF; …" db.statement="\n\nPRAGMA foreign_keys = OFF;\nBEGIN\nTRANSACTION;\nINSERT\n  OR REPLACE INTO Hentai (\n    id,\n    cover_type,\n    media_id,\n    num_favorites,\n    num_pages,\n    page_types,\n    scanlator,\n    title_english,\n    title_japanese,\n    title_pretty,\n    upload_date\n  )\nVALUES\n;\nINSERT\n  OR REPLACE INTO Tag (id, name, type, url)\nVALUES\n;\nCOMMIT;\nPRAGMA foreign_keys = ON;\n" rows_affected=0 rows_returned=0 elapsed=137.1µs elapsed_secs=0.0001371
                      [nhentai_archivist::search_api] INFO  Downloaded hentai metadata page 1 / 0.

**Comment by 9-FS** [comment]
`NHENTAI_TAGS` is not properly formatted. Looks like you've copied the `docker-compose.yaml` example's formatting instead of the `.env`'s. They are slightly different, unfortunately.

**Comment by YaBoyHankHill** [comment]
Ah, I see now. Forgot the apostrophes sandwiching each tag. Works now with the updated format, Thanks for the assist!
