### ISSUE TITLE
Folders not removing after download

### ISSUE THREAD

**Issue by soultaco83** [9-FS/nhentai_archivist#52]
version: 3.6.2
After updating the docker to 3.6.2
Once the file is compressed to .cbz but the folder is left empty in location. 
reverting to 3.6.1 resolves and the empty folder is removed after the cbz is created.

**Comment by 9-FS** [comment]
Thanks for reporting. Fixed in version 3.6.3.

**Comment by soultaco83** [comment]
Confirmed resolved on 3.6.3
