### ISSUE TITLE
Trimming overly long titles

### ISSUE THREAD

**Issue by Morvire** [9-FS/nhentai_archivist#53]
Some mangas have very long titles that exceed the allowed byte length. The program simply displays the `ERROR Saving hentai failed with: Syntax error in the file name, folder name, or volume label. (os error 123)` instead of truncating the title. They are added to the database, but the archive cannot be created.

Example:

![image](https://github.com/user-attachments/assets/e8a51d87-b7fe-412d-bb6c-57476de6e095)

I suggest automatically truncating titles that are longer than 243 bytes. Alternatively, this could be done through a parameter in the `.env ` file.

**Comment by 9-FS** [comment]
Gude Morvire, thanks for your report. This is already supposed to be implemented https://github.com/9-FS/nhentai_archivist/blob/2fe4d7dbb5a44f68633172a7858ef2f1d2122b6d/src/hentai.rs#L125-L138 and had been tested on my Linux machine during initial development. Please confirm your operating system, the nHentai Archivist version you are using, and give an example of a specific hentai that fails including logs made with `DEBUG = true`.

**Comment by Morvire** [comment]
OS: `Windows 10 Pro 22H2 (Build 19045.5198)`
nHentai Archivist version: `2024-11-28.nhentai_archivist.3.6.3.x86_64-pc-windows-gnu.exe`
Log file: [2024-12-04T13_09.log](https://github.com/user-attachments/files/18008841/2024-12-04T13_09.log)
Codes that definitely don't work: 
- 540872
- 530509
- 522063
- 522041
- 521506
- 499042
- 437961
- 414309
- 407803
- 376254

**Comment by Morvire** [comment]
@9-FS 
After further investigation, I believe the issue lies in how filenames are truncated when handling titles with multi-byte characters (e.g., Japanese, Chinese, or emojis) encoded in UTF-8. Let me explain the problem and why it could be causing failures specifically on Windows.

The filename truncation logic currently uses the `graphemes(true)` iterator, which correctly handles graphemes. However, the actual calculation of the filename's byte size in this block of code is flawed:
```
cbz_filename = cbz_filename
    .graphemes(true) // iterate over graphemes
    .take_while(|&g| // only add grapheme if it wouldn't bust limit
    {
        byte_count += g.len() as u16; // Incorrectly assumes g.len() gives byte size
        byte_count <= FILENAME_SIZE_MAX - 12
    }) // limit title to 243 B so filename does not exceed 255 B
    .collect();
```
Here’s the issue:

- `g.len()` measures the **number of characters** in the grapheme, **not the actual byte size** of the grapheme when encoded in UTF-8.
- UTF-8 characters can take anywhere from 1 to 4 bytes:
  - **ASCII characters** (like `a`, `b`, `c`) are 1 byte.
  - **Japanese Kanji, Chinese characters, and others** can be 3 bytes each.
  - **Emojis** or complex graphemes can be 4 bytes each.
- As a result, the calculated `byte_count` may **underestimate the actual byte size**, especially when the title includes multi-byte characters like Japanese text or emojis. This can cause the final filename to exceed the 255-byte limit imposed by Windows, leading to the error `Syntax error in the file name, folder name, or volume label. (os error 123)`.

The truncation logic needs to accurately calculate the size of each grapheme in **bytes** rather than assuming `g.len()` corresponds to its byte size. This can be fixed by using `g.as_bytes().len()` to measure the actual UTF-8 byte size of each grapheme.

Here's my suggestion:
```
if FILENAME_SIZE_MAX - 12 < cbz_filename.len() as u16 // if title size problematic
{
    let mut byte_count: u16 = 0;
    cbz_filename = cbz_filename
        .graphemes(true) // iterate over graphemes
        .take_while(|&g| // only add grapheme if it wouldn't bust limit
        {
            byte_count += g.as_bytes().len() as u16; // Correctly calculate UTF-8 byte size
            byte_count <= FILENAME_SIZE_MAX - 12
        })
        .collect();
}
```

**Comment by Morvire** [comment]
Solved!
