### ISSUE TITLE
Arch Can't Mass Download

### ISSUE THREAD

**Issue by altaccou** [9-FS/nhentai_archivist#8]
I'm following the guide to use this program, and trying to mass download everything. This is the code I'm using:

CF_CLEARANCE = ""
CSRFTOKEN = "[REDACTED]"
DATABASE_URL = "./db/db.sqlite"
DOWNLOADME_FILEPATH = "./config/downloadme.txt"
LIBRARY_PATH = "./hentai/"
LIBRARY_SPLIT = 10000
NHENTAI_TAG = "['language:"english"']
SLEEP_INTERVAL = 50000
USER_AGENT = "[REDACTED]"

If I'm using direct IDs for the comics, it does work. I've also tried the above code without the DOWNLOADME_FILEPATH and it still didn't work.

**Comment by altaccou** [comment]
nvm i fixed it. if you're on linux, make sure you run it in terminal instead of just double clicking it. since it isn't a .sh file, it won't open the GUI, so if you don't have a downloadme.txt file, it just won't work.

**Comment by 9-FS** [comment]
This is interesting. I am using Fedora with KDE and attaching the `.sh` file extension does not make a difference for me and I assumed `.sh` stands for bash scripts. Would it be more idiomatic to add the extension?

**Comment by altaccou** [comment]
It could just be an issue with Arch itself. I might try playing around with it and see if I can get it to directly open in Konsole. When I was testing it earlier, it just acted as if it were an executable and just ran in the background without any GUI. And, with the code I was using, the issue I had was that I used NHENTAI_TAG instead of NHENTAI_TAGS.
